Don't use package-lock.json
Assuming we can stick with the old package.json approach:
https://www.codementor.io/johnkennedy/get-rid-of-that-npm-package-lock-json-e0bj7ai42

Fixes build error:
ERROR: files left in build directory after distclean:
./package-lock.json