Fix manifest parsing causing OBS build failure
Since there are no longer any "prod" runtime dependencies listed in a
"dependencies" node in package.json, the parser never sets the pkg_deps
variable, resulting in an unreferenced variable exception:

  ./node-pkg-info.py package.json --diff prod --format install > debian/eos-node-modules.install
  Traceback (most recent call last):
    File "./node-pkg-info.py", line 175, in <module>
      main(args.diff_type, args.fmt, args.package_manifest_path)
    File "./node-pkg-info.py", line 141, in main
      prod_pkgs, dev_pkgs = package_manifest_modules(pkg_json_path)
    File "./node-pkg-info.py", line 75, in package_manifest_modules
      return pkg_deps, pkg_dev_deps
  UnboundLocalError: local variable 'pkg_deps' referenced before assignment

Preset both the "prod" and "dev" dependencies to an empty list to guard
against either key missing from package.json.